### PR TITLE
ValidateStruct: Go through all fields instead return immediately on first error

### PR DESCRIPTION
**Pull request by bom-d-van**
@asaskevich awesome works. Thanks. :)

### CODE REVIEW

**Comment by imothee** [comment]
Thank you! 
I agree with the formatting and the returned data structures and was just about to write this myself.

**Comment by bom-d-van** [comment]
> Thank you! 
> I agree with the formatting and the returned data structures and was just about to write this myself.

Cool. If it's alright, could you merge the request?

**Comment by asaskevich** [comment]
@bom-d-van @imothee thanks, looks great :+1:

**Comment by bom-d-van** [comment]
:+1:

**Comment by imothee** [comment]
I did not actually check the low level code for validity but I think there are some problems with the way the casting/assignment in the commit is done.

Eg. validateStruct returns a type error which cannot be ranged as type Errors. Additionally, Errors is a slice of type error, not Error.

It also returns different types "error" vs Error vs Errors in different sections. There should be more consistency with typeCheck returning *Error or only "error" types rather than Error{t.Name, err} in some cases.

I would be happy to work on a better way of managing consistency as I think it is important.

**Comment by bom-d-van** [comment]
IMO, I think returning an error is more natural in the world of go.
If you don't care about the error content and just want to stop the processing of your program, you just check `if err != nil`. If you want to inspect the error, you could do:

```golang
if errs, ok := err.(govalidator.Errors); ok {
    for _, err := range errs {
        if e, ok := err.(govalidator.Error); ok { ... }
    }
}
```

This change offers us the capability to inspect the error without changing the original api. However, this is just my opinion, may be you have a better idea. Looking forward to yours.

**Comment by imothee** [comment]
Good point, I see what you were trying to achieve now and agree that keeping API consistency is a good thing. Thank you for explaining that.

My mental complexity is mapping in validation 'fails' with normal error cases. In my perfect world you would have something more like

valid, invalidFields, err := validateStruct()
Because to me, separating an error occurred (ie. if the library had to validate against a server and there was a network issue) from "these fields are invalid" makes more sense and leads to more explicit code.

However I was not considering breaking changes to the API and I agree that returning an error as the error itself is more natural so I am happy to deal with the complexity in my code and not the library!

**Pull request merged**
