### PR TITLE
Issue #62 and #66 improvements to IsURL

### PR DESCRIPTION
**Pull request by nathj07**
The process here was to create a few unit tests to prove the issues #62 and #66. 

To then ensure they passed I have made a slight amend to the regex and actually put some final checking type code into `IsURL` in `validator.go`. 

All tests now pass and I think this resolves the issues. If there are any other changes/feedback/tests then let me know and I'll get to as soon as I can.

### CODE REVIEW

**Comment by nathj07** [comment]
Note: the final commit references the wrong issue number

**Comment by asaskevich** [comment]
Thank you, it's working fine :+1: Issues can be closed.

**Comment by antonsekatski** [comment]
Sadly but it's still not working correctly: `govalidator.IsURL("google")` - it's not a valid url but it returns `true`

**Comment by nathj07** [comment]
Hmm, I'm away from my machine at the moment. I can try to take a look next
week.

**Pull request merged**
