### PR TITLE
[TASK] Add range

### PR DESCRIPTION
**Pull request by genofire**
Untested ...

---
This change is [Reviewable](https://reviewable.io/reviews/asaskevich/govalidator/190)

### CODE REVIEW

**Comment by marcobeierer** [comment]
@genofire 
I had a quick look at your implementation and see two problems:

1. This only works on string values and not on int/int64 values because of the check at https://github.com/asaskevich/govalidator/blob/master/validator.go#L828 . I think a clean solution would require some changes to the ParamValidator in general, because it only supports string values currently.
2. It does not allow negative ranges like for example `range(-3|5)`. This could easily fixed in the regular expression.

**Comment by asaskevich** [comment]
@genofire @marcobeierer Could you add some tests before merging please?

**Comment by marcobeierer** [comment]
@genofire @asaskevich I could fix point 2 and implement some tests in the next days. I will also have a look at my first point above, but am not sure anymore if the conclusion is correct. I implemented `range` as a custom validator and therefore some additional changes were necessary, but I have to recheck if this is also true for the native solution of @genofire.

**Comment by genofire** [comment]
lol, i have not found time to write tests ...
(not sure about the way on this repo ...)

**Pull request merged**
