### PR TITLE
fix: include major in go.mod module directive

### LINKED ISSUE #384: Make the release tags version go mod compatible.
It would be great to have the tagged release be named in the format vX.X.X format so that go mod can read it. Else the mod file shows something like github.com/asaskevich/govalidator v0.0.0-20200108200545-475eaeb16496 which is not very readable and difficult to upgrade.

### PR DESCRIPTION
**Pull request by nightah**
|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix         | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

This change includes the major version in the module path.
This will ensure appropriate semver tagging.

Closes #384.

### CODE REVIEW

**Review by marclop — APPROVED** [review]
Would love to have this merged.

**Comment by marclop** [comment]
@asaskevich any reason not to comply and update the `go.mod` file to make it compatible with Go modules?

**Comment by sergeyglazyrindev** [comment]
Hello guys!
I forked this package cause owner disappeared. Hope, he will be back, but it would be easier to merge these changes back if he is back
Link to my repo: create issue there and we'll discuss it.

**Comment by tboerger** [comment]
It would be great to get this merged, currently [renovate](https://github.com/apps/renovate) seems to be not able to update the dependency automatically because of the go.mod definition :(

**Comment by phil9909** [comment]
@sergeyglazyrindev it looks like you have merge permission on this repo now.

Could you maybe have a look at this PR? Currently, the repo can't be used cleanly in go module based projects.

**Comment by sergeyglazyrindev** [comment]
I don't have write access here.

**Pull request merged**
