### PR TITLE
skip all struct fields tagged with `valid:"-"`

### PR DESCRIPTION
**Pull request by oryband**
proposed fix for #58

### CODE REVIEW

**Comment by oryband** [comment]
@asaskevich please make sure i didn't break anything

**Comment by oryband** [comment]
@bolshoy

**Comment by asaskevich** [comment]
All fine, but I'm not sure about issue that you referenced to this PR. I will try to take a look on it in short time

**Comment by asaskevich** [comment]
#58 Issue require some test cases with which I can be sure that's all ok

**Pull request merged**
