### PR TITLE
Added Original Struct to CustomTypeTagMap

### PR DESCRIPTION
**Pull request by alessandropietrobelli**
In case on custom validators needs to check parent struct or slices,
like on my case, current struct (o) isn’t enough, so I’ve added the
entire original struct

---

This change is [Reviewable](https://reviewable.io/reviews/asaskevich/govalidator/144)

### CODE REVIEW

**Comment by asaskevich** [comment]
It will break back compatibility. Could you please put info about changes into the following section of README?

**Comment by alessandropietrobelli** [comment]
Hi @asaskevich , what do you think if I write on README that this changes are related to new version called v5?

Let me know

**Comment by alessandropietrobelli** [comment]
I've also added this to descrive custom error messages

###### Custom error messages
Put ~ after validator to display your custom error message

From v5 and above, you can use %s to return the value

```go
import "github.com/asaskevich/govalidator"

type Driver struct{
	Name string `valid:"-"`
    Car CustomCarType `valid:"customCarTypeValidator~Custom Error Message"`
}

// v5 and above
type Driver struct{
	Name string `valid:"-"`
    Car CustomCarType `valid:"customCarTypeValidator~Custom Error Message value %s not valid"` //Add %s if you want to return current value
}
```

**Comment by asaskevich** [comment]
Yeah, I can accept it 😄 but what about multiple validators, e.g.:
```go
type Driver struct{
    Name string `valid:"-"`
    Car CustomCarType `valid:"customCarTypeValidator1,customCarTypeValidator2~Custom Error Message"`
}
```

**Comment by alessandropietrobelli** [comment]
Nice question, as it is structured now the code it will print the same error message

**Comment by asaskevich** [comment]
Hi, sorry for the delay.

I meant two validators with two custom messages:
```go
type Driver struct{
    Name string `valid:"-"`
    Car CustomCarType `valid:"customCarTypeValidator1~First Error,customCarTypeValidator2~Second Error"`
}
```
Will it print two messages or only first failed if both of validators will be failed?

**Comment by asaskevich** [comment]
@alessandropietrobelli, look at example above, will it print two messages or only first if both of validators will fall? I would like to merge it, but there is misunderstanding with behavior of function

**Comment by asaskevich** [comment]
@alessandropietrobelli sorry for no actions with this pull request for so long time. Could you resolve conflicts with current version of package and I will be able to merge it, please?

**Comment by alessandropietrobelli** [comment]
Hi Alex,
I will check and let you know in the next days.

Thank you

Ale

**Comment by alessandropietrobelli** [comment]
Hi Alex,
faster than I thought.

It should work, check it

**Comment by asaskevich** [comment]
Hi @alessandropietrobelli there are some failed tests
```./validator_test.go:11:66: cannot convert func literal (type func(interface {}, interface {}) bool) to type CustomTypeValidator
./validator_test.go:14:65: cannot convert func literal (type func(interface {}, interface {}) bool) to type CustomTypeValidator
./validator_test.go:2817:48: cannot convert func literal (type func(interface {}, interface {}) bool) to type CustomTypeValidator
```
Could you check it please?

**Comment by asaskevich** [comment]
@alessandropietrobelli could you check failed tests, please?

**Comment by sergeyglazyrindev** [comment]
Hello guys!
I forked this package cause owner disappeared. Hope, he will be back, but it would be easier to merge these changes back if he is back
Link to my repo: create issue there and we'll discuss it.

**Pull request closed without merging**
