### PR TITLE
Added new feature - configuring custom error message

### PR DESCRIPTION
**Pull request by chatwithrajaram**
Added new feature - configuring custom error message

---
This change is [Reviewable](https://reviewable.io/reviews/asaskevich/govalidator/121)

### CODE REVIEW

**Comment by waltton** [comment]
Running some tests I saw some problems.
Seems that you remove the function IsHost by mistake.
Also in validator_test.go at the line 2265 there's the error "too few values in struct initializer". To fix it, the fields could by named, or the third field need to be passed.

**Comment by asaskevich** [comment]
Yes, there are some problems, I'm not able to merge it until these'll not resolved

**Comment by annismckenzie** [comment]
Erm, this is weird. Why did you merge this when a) the Wercker build failed and b) the `IsHost` function was removed (as noted above by @waltton)?

**Comment by asaskevich** [comment]
@annismckenzie I resolved problems in my commit before the merge (https://github.com/asaskevich/govalidator/commit/6e6a915217c1762995302368a4e880b84e3daf2a) :)

**Comment by annismckenzie** [comment]
Oh, now I see. Should've taken a look at the merge commit. Still, it might be better in the future to fix these mistakes in a commit and push it to the merge request. :)

**Comment by Raggaer** [comment]
Is there any example on how to add a custom message? Thanks

**Comment by wilsontamarozzi** [comment]
Custom message example
```golang
`valid:"required~My custom message for require,length(2|60)~My custom message for lenght"`
```

**Comment by gummybears** [comment]
Tried to validate a record with a custom message like explained, but it does not work. I see 
empty records appearing in the database. 
```
package main

import (
  "fmt"
  "time"
  "github.com/asaskevich/govalidator"
)

type Ticket struct {
  Id        int64     `json:"id"`
  FirstName string    `json:"firstname" valid:"required-First name is blank"`
  LastName  string    `json:"lastname"  valid:"required-Last name is required"`
  Email     string    `json:"email"     valid:"required-Email is required"`
  Licence   string    `json:"licence"   valid:"required-Licence plate is required"`
  Complaint string    `json:"complaint" valid:"required-Complaint is required"`
  Date      string    `json:"datum"`
  CreatedAt time.Time `json:"createdAt"`
  UpdatedAt time.Time `json:"updatedAt"`
  DeletedAt time.Time `json:"-"`
}

func main() {
  lv_ticket := Ticket{}
  _, lv_err := govalidator.ValidateStruct(lv_ticket)
  fmt.Printf("error should be set, but is not '%v'\n",lv_err)
}
```

**Comment by asaskevich** [comment]
@gummybears did you attempted to use `~` symbol instead of `-`?
```
type Ticket struct {
  Id        int64     `json:"id"`
  FirstName string    `json:"firstname" valid:"required~First name is blank"`
...
```

**Comment by gummybears** [comment]
Hmm, no, but to be honest I found the go-ozzo/ozzo-validation package easier to use.
Thanks for your help.

**Pull request merged**
