### PR TITLE
Support for RFC 3339 validation

### PR DESCRIPTION
**Pull request by yezooz**
Adds IsRFC3339 function for checking if string is matching [RFC 3339 spec](https://www.ietf.org/rfc/rfc3339.txt).

---
This change is [Reviewable](https://reviewable.io/reviews/asaskevich/govalidator/176)

### CODE REVIEW

**Comment by bbrks** [comment]
Hi @yezooz,

I have a suggestion for this validator. Rather than relying on regexp, you can use the `time.Parse()` function from stdlib to validate for RFC3339.

Let me know what you think.

Here's a benchmark and some example code I threw together.
You can see from the benchmarks it's roughly twice as fast:

```
10:37 $ go test -v -bench .
=== RUN   TestIsRFC3339
=== RUN   TestIsRFC3339New
--- PASS: TestIsRFC3339 (0.00s)
--- PASS: TestIsRFC3339New (0.00s)
BenchmarkIsRFC3339-8      	  200000	      6078 ns/op
BenchmarkIsRFC3339New-8   	  500000	      3281 ns/op
PASS
ok  	github.com/bbrks/tmp	2.958s
```

## main.go
```go
package main

import (
	"regexp"
	"time"
)

var rxRFC3339 = regexp.MustCompile(`^([0-9]+)-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])[Tt]([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9]|60)(\.[0-9]+)?(([Zz])|([\+|\-]([01][0-9]|2[0-3]):[0-5][0-9]))$`)

func IsRFC3339(str string) bool {
	return rxRFC3339.MatchString(str)
}

func IsRFC3339New(str string) bool {
	_, err := time.Parse(time.RFC3339, str)
	return err == nil
}
```

## main_test.go
```go
package main

import "testing"

var tests = []struct {
	param    string
	expected bool
}{
	{"2016-12-31 11:00", false},
	{"2016-12-31 11:00:00", false},
	{"2016-12-31T11:00", false},
	{"2016-12-31T11:00:00", false},
	{"2016-12-31T11:00:00Z", true},
	{"2016-12-31T11:00:00+01:00", true},
	{"2016-12-31T11:00:00-01:00", true},
	{"2016-12-31T11:00:00.05Z", true},
	{"2016-12-31T11:00:00.05-01:00", true},
	{"2016-12-31T11:00:00.05+01:00", true},
}

func TestIsRFC3339(t *testing.T) {
	t.Parallel()
	for _, test := range tests {
		actual := IsRFC3339(test.param)
		if actual != test.expected {
			t.Errorf("Expected IsRFC3339(%q) to be %v, got %v", test.param, test.expected, actual)
		}
	}
}

func TestIsRFC3339New(t *testing.T) {
	t.Parallel()
	for _, test := range tests {
		actual := IsRFC3339New(test.param)
		if actual != test.expected {
			t.Errorf("Expected IsRFC3339(%q) to be %v, got %v", test.param, test.expected, actual)
		}
	}
}

func BenchmarkIsRFC3339(b *testing.B) {
	for i := 0; i < b.N; i++ {
		for _, test := range tests {
			IsRFC3339(test.param)
		}
	}
}

func BenchmarkIsRFC3339New(b *testing.B) {
	for i := 0; i < b.N; i++ {
		for _, test := range tests {
			IsRFC3339New(test.param)
		}
	}
}
```

**Comment by yezooz** [comment]
Hi @bbrks 

It's a great suggestion, I'll implement it this way.

Thanks

**Comment by asaskevich** [comment]
Maybe create alias, something like "isTimestamp" or "IsISODate" ?

**Comment by yezooz** [comment]
Sure, could do that

**Comment by bbrks** [comment]
@asaskevich I advise `IsTime(str, format string)` which would accept constants from [Go's time package](https://golang.org/pkg/time/#pkg-constants) or custom formats.

Then `IsRFC3339()` can be changed to:

`return IsTime(str, time.RFC3339)`

**Comment by asaskevich** [comment]
@yezooz can you make proposed changes with second argument? I'll merge it

**Comment by yezooz** [comment]
@asaskevich yep, will do

**Comment by yezooz** [comment]
@asaskevich kept `IsRFC3339` but it now relies on new `IsTime` function as @bbrks suggested

**Comment by asaskevich** [comment]
Great!

**Pull request merged**
