### PR TITLE
Fix validator processing errors

### PR DESCRIPTION
**Pull request by KonishchevDmitry**
The following bugs have been fixed:
- ValidateStruct() didn't return an error if an invalid validator was specified in the struct validation tags.
- Built-in validators weren't processed when a custom validator was specified.

This commit adds a check which ensures that the value is checked against all specified validators before return that the value is valid.

---

This change is [Reviewable](https://reviewable.io/reviews/asaskevich/govalidator/158)

### CODE REVIEW

**Comment by kohkimakimoto** [comment]
I need it. Can you please merge it?

**Comment by asaskevich** [comment]
@KonishchevDmitry thanks
@kohkimakimoto yes, already

**Comment by asaskevich** [comment]
There are failed tests:
```
--- FAIL: TestCustomValidator (0.00s)
	validator_test.go:2089: Got an unexpected result for struct with custom always false validator: true %!s(<nil>)
```
@KonishchevDmitry @kohkimakimoto can you review it?

**Comment by kohkimakimoto** [comment]
The validators don't be processed if the validated value is empty. 

see https://github.com/asaskevich/govalidator/blob/master/validator.go#L754

But In`TestCustomValidator`, the tested structs don't have a value. I think that these test code are incorrect. I'll fix the test code by another PR.

**Comment by kohkimakimoto** [comment]
Please review it.

**Comment by KonishchevDmitry** [comment]
> But in TestCustomValidator, the tested structs don't have a value. I think that these test code are incorrect. I'll fix the test code by another PR.

@kohkimakimoto, @asaskevich, but why? I can understand that all predefined validators have the "default behaviour" that they validate only non-zero values, but why we should apply this behaviour to custom validators? In my world "custom" means, that you can write something beyond the defaults. There are a lot of cases, when this decision to not check zero values is not suitable for us. The Go's world, I think, is the only place where missing value is equal to empty value, and if we don't give to custom validators an ability to override this default, we won't be able to properly validate JSON requests which are designed with traditional notion that empty value is not equal to missing value.

So I intentionally placed custom validators check before
```go
if isEmptyValue(v) {
		// an empty value is not validated, check only required
		return checkRequired(v, t, options)
}
```
and wrote these tests intentionally with empty structs to check that custom validators are always processed, even when the data is empty, because the only one who knows how to handle empty values - is the custom validator's logic.

**Comment by kohkimakimoto** [comment]
@KonishchevDmitry I don't know that the reason to check empty values before custom validators are processed. But this behavior was committed intentionally by https://github.com/asaskevich/govalidator/pull/158/commits/e31e072e4202b573c60052012a798ccc332daccc. So I thought that I should follows this behavior and I fixed test code.

I think that your question is good. Please discuss it with @asaskevich

**Comment by richardlt** [comment]
Found another problem with this feature, i'm using *string as a field i want to validate like that valid:"url,length(0|100),optional", because it's a pointer the method will recursively call typeCheck at the end of the switch/case. In the inner call of typeCheck for string value if my field is an empty string the isEmptyCheck will return with true value because it's an optional field. But because options list entries were not deleted the defer from the first typeCheck call will return an error.

**Pull request merged**
