### PR TITLE
Update validator.go

### PR DESCRIPTION
**Pull request by aymane-mzily**
Update IsEmail function to validate RFC5332 email

---
This change is [Reviewable](https://reviewable.io/reviews/asaskevich/govalidator/254)

### CODE REVIEW

**Comment by asaskevich** [comment]
Could you merge #254 and #253 together, please?

**Comment by blind-oracle** [comment]
I'd kinda wanted to make the LookupMX functionality optional.

Maybe we should add another function that does the same but without lookup?
Because in worst case this call can take several seconds (in case of DNS or network fuckup) and in many cases it's not tolerable.

**Comment by asaskevich** [comment]
@blind-oracle yes, it makes sense
@aymane-mzily current merged implementation will go to another function, something like `IsEmailExists`, and the previous implementation based on regexp will be returned as pure `IsEmail` function.

**Comment by asaskevich** [comment]
Fixed https://github.com/asaskevich/govalidator/commit/7d2e70ef918f16bd6455529af38304d6d025c952#diff-2c21fb78980d1744f15f8637f5c8700bR55

**Pull request merged**
