### PR TITLE
Fix ErrorsByField when using custom validators

### LINKED ISSUE #133: Panic on ErrorsByField
When using `ValidateStruct` on a structure that has a field that uses a custom validator, if there are several errors `ErrorsByField` panics on this [line](https://github.com/asaskevich/govalidator/blob/c541dfccfaabfd9e026eb1821cfec90a503ba6fc/validator.go#L906).

It is because the `Errors` list contains both `Error` and `Errors`.

Here is an example that you can copy paste:

```go
package main

import (
	"time"

	"github.com/asaskevich/govalidator"
)

type Something struct {
	Name string    `valid:"required,length(3|10)"`
	Date time.Time `valid:"custom-time"`
}

func main() {
	govalidator.CustomTypeTagMap.Set("custom-time", govalidator.CustomTypeValidator(func(data interface{}, obj interface{}) bool {
		return false
	}))

	a := Something{}
	_, err := govalidator.ValidateStruct(&a)
	if err != nil {
		govalidator.ErrorsByField(err) // panic
	}
}

```

### PR DESCRIPTION
**Pull request by asdine**
Fixes #133

---
This change is [Reviewable](https://reviewable.io/reviews/asaskevich/govalidator/134)

### CODE REVIEW

**Comment by mwmahlberg** [comment]
lgtm Have it running on a project.
Maybe we could add the functionality that actually for nested structs, the parent struct name would be added to the error message. For example ``Name.First`` instead of ``Name`` That should be relatively easy when making
```
ErrorsByField(e error)map[string]string
```
call something like

```
errorsByField(prefix string, e error) map[string]string
```

when entering the recursion.

**Comment by mwmahlberg** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/asaskevich/govalidator/134)*

**Comment by LennartOlsen** [comment]
@mwmahlberg i like your idea of adding a prefix, but it seems that another soultion to actually follow the structure would be nicer like maybe:
```
error = map[string]interface{} = {
     "name":string("error")
     "childobject": map[string]string = {
          "childname":string("error")
     }
}
```
@asaskevich what is the ETA of this pull request?

**Comment by krak3n** [comment]
Ended up doing this for the time being:

``` go
	errors := map[string]string{}
	for _, err := range errs {
		gvErrors := err.(govalidator.Errors)
		for _, gvError := range gvErrors {
			e := gvError.(govalidator.Error)
			validationErrors[strings.ToLower(e.Name)] = strings.TrimSpace(e.Err.Error())
		}
	}
```

**Comment by asaskevich** [comment]
@LennartOlsen already, sorry for two-month delay 😞

**Pull request merged**
